name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clone the repository
        uses: actions/checkout@v3

      - name: 📦 Set up Python and dependencies
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: 📌 Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🧪 Run Unit Tests
        run: |
          export PYTHONPATH=$PWD  # ✅ Ensures Python recognizes project root
          pytest tests/
